require("settings._general")

require("plugins")

require("settings.treesitter")
require("settings.lualine")
require("settings.telescope")
require("settings.lsp")
require("settings.cmp")
require("settings.dap")
require("settings.crates")
require("settings.sessions")
require("settings.gitsigns")
require("settings.diffview")
require("settings.project")
require("settings.fidget")
require("settings.rust")
require("settings.leap")
require("settings.auto-pairs")
require("settings.copilot")
require("settings.goto-preview")
